- .gitignore
- README.md
- py_loobas/models.py
- py_loobins/models.py
- pyproject.toml
Added Pydantic models to represent  LOOBins and its associated components.
> Add Pydantic model

- src/pyloobins/cli.py
- src/pyloobins/util.py
- Commits on Mar 13, 2023
[Added create-template command](https://github.com/infosecB/LOOBins/commit/d9510d8baf815f5a592bf12a62656c0aac4ad3b3)
- [Added make_template function](https://github.com/infosecB/LOOBins/commit/983fb249bfe98393ffdef4c84285726c4c5da165)
> Add function/command for creating a template yaml file

- src/pyloobins/models.py
- src/pyloobins/util.py
- Renamed function classes (NameCls convention)
- Added Functions class attributes
- Updated make_tempklate function to account for above changes
> Multiple model, util fixes

- pyproject.toml
- src/pyloobins/cli.py
- src/pyloobins/models.py
- src/pyloobins/util.py
- [Add tool.poetry.scripts stanza for cli](https://github.com/infosecB/LOOBins/commit/52729be00a967433e58d6710391e0ed42078e43b)
- [Complete create_template function & command](https://github.com/infosecB/LOOBins/commit/1cf94eabcfee465ae7ed92021f2118d9efbf3823)
- [Clean up models, add LOOBin yaml method](https://github.com/infosecB/LOOBins/commit/310a36fe6e047a16d583d19d246da89bdecb2b1c)
- [Cleanup, add normalize_file_name function](https://github.com/infosecB/LOOBins/commit/01ada2b46cf8899d263153e372ba4cd1ae762fbf)
> Add functions, cli to create LOOBin .yml template file.

- pyproject.toml
- src/pyloobins/cli.py
- src/pyloobins/models.py
- src/pyloobins/templates/loobin.md.j2
- src/pyloobins/util.py
- Significant modifications to the LOOBin model
- Tweak util functions to account for new LOOBin model
- Create Jinja template for LOOBin-Web content creation
> LOOBin model overhaul, util defs, Jinja template

- .gitignore
- pyproject.toml
- src/pyloobins/cli.py
- [Fix to_yaml method call](https://github.com/infosecB/LOOBins/commit/86d495ff4da16d1fec206fbf7c3d809f3a0e10cb)
- [Add .DS_Store](https://github.com/infosecB/LOOBins/commit/00f981585f4e834204096f40cb01fde8a2cea98e)
- [Add include for LOOBins folder](https://github.com/infosecB/LOOBins/commit/8ced67f85946bbb6b61091cc13f4a7900d4c865b)
- [Fix path variable](https://github.com/infosecB/LOOBins/commit/005c925d0f17106622e89a6407f5af59e4bd875a)
> Small fixes

- LICENSE
- pyproject.toml
- [Add GNU GPL3 license](https://github.com/infosecB/LOOBins/commit/8aa919f7936ad3ee28d20a33963e7fbcf96c0186)
- [Add homepage, repo, keywords](https://github.com/infosecB/LOOBins/commit/8c556a081caa36367341de93ad47071f821441b7)
> Add license, add context to Poetry package config

- pyproject.toml
- [Fix LOOBins include, bump version](https://github.com/infosecB/LOOBins/commit/87e2ce0c793e7488142cce9d0ac8f85f7a592b13)
- [Add license to poetry config](https://github.com/infosecB/LOOBins/commit/89f4abe0a5c643f0660b119794aabb7ff9fe44d6)
> Minor pyproject.toml config fixes

- pyproject.toml
- src/pyloobins/util.py
- [Add function to load LOOBin yaml files](https://github.com/infosecB/LOOBins/commit/1bd109cb215637efcc3d58dea677261492f2373e)
> Add function to load LOOBin yaml files

- pyproject.toml
- [Bumped version number to 0.1.2](https://github.com/infosecB/LOOBins/commit/da4d9962616ef77757094adb55e4e793e3b26cd0)
> Bumped version number to 0.1.2

- .github/ISSUE_TEMPLATE/new_loobin.yml
- CONTRIBUTING.md
- Closes #18
- [Add New LOOBin issue template](https://github.com/infosecB/LOOBins/commit/499a89dc66c7f0588306236fced695b4424aa9f6)
- [Initial commit of contrib doc](https://github.com/infosecB/LOOBins/commit/b1211681a9fc3c2cf09af57806a59d3341c28c27)
- [Add textarea](https://github.com/infosecB/LOOBins/commit/40bf52d2da131c965d1139c411ac984feab1df10)
> Add instructions for contributing LOOBins

- CONTRIBUTING.md
[Add more detail to contrib](https://github.com/infosecB/LOOBins/commit/279b2445e5ff905125b3855914b490502d871586)
> Add more detail to contrib

- CONTRIBUTING.md
- [Add SchemaStore details](https://github.com/infosecB/LOOBins/commit/82b162284266c931f99c587c942f7874f54c75fb)
> Add SchemaStore details

- pyproject.toml
- src/pyloobins/cli.py
- [Add sys.exit to validate cmd](https://github.com/infosecB/LOOBins/commit/b8558e5136e893e448a8628cc20a1fd8e33b68d2)
- [Bump pyloobins version](https://github.com/infosecB/LOOBins/commit/09ba5f9fc083fe10d6ad1262afa0cc5eca385a72)
> Add validate exit

- LOOBins/osascript.yml
- [Indent tactics and tags nodes](https://github.com/infosecB/LOOBins/commit/b96a146803aafef0466e051572545350e5ac9083)
> osascript fix

- LOOBins/mdfind.yml
Added mdfind binary which is a command line alternative to the GUI Spotlight in MacOS.
> Adding YAML file for mdfind binary

- LOOBins/ioreg.yml
Added use of the ioreg binary to check whether a target macOS host's screen is locked or not.
> Adding YAML file for ioreg binary

- LOOBins/security.yml
- [Add security.yml](https://github.com/infosecB/LOOBins/commit/9270b6cb5f334fe6e15cc8a155806354194c3afc)
- Closes #60
> Add LOOBin for security

- LOOBins/GetFileInfo.yml
Add GetFileInfo binary which returns the type, creator, attributes, created, and modified file information of a file or directory.
> Add YAML file for GetFileInfo binary

- LOOBins/SetFile.yml
Uses the CommandLine/Terminal to set file and or directory attributes. It can set attributes, creator, creation date, modification date, and file type for multiple files at a time.
> Add YAML file for SetFile binary

- LOOBins/ioreg.yml
- LOOBins/osascript.yml
Added some additional examples for the ioreg binary
> Updating ioreg, osascript with additional command examples.

- LOOBins/last.yml
- [Add last.yml](https://github.com/infosecB/LOOBins/commit/5d77511663e986a0a52d9856451ad576c1a74830)
- Closes #54
> Add YAML file for last

- LOOBins/screencapture.yml
- Closes #14 
- [Add LOOBin for screencapture](https://github.com/infosecB/LOOBins/commit/a9ba5709241c14e8b1efaa8e7419862e30816032)
> Add LOOBin for screencapture

- src/pyloobins/models.py
> Dedup tags/tactics in LOOBins combine_ methods

- LOOBins/GetFileInfo.yml
- LOOBins/SetFile.yml
- LOOBins/dscl.yml
- LOOBins/ioreg.yml
- LOOBins/mdfind.yml
- LOOBins/networksetup.yml
- LOOBins/osascript.yml
- LOOBins/pbpaste.yml
- LOOBins/softwareupdate.yml
- LOOBins/sysctl.yml
- src/pyloobins/templates/loobin.md.j2
- [Fix code section, detection url](https://github.com/infosecB/LOOBins/commit/5edab73fc5bb0628c76e001808e59e0fe9700694)
- [Fix blank detection URL](https://github.com/infosecB/LOOBins/commit/4a104b4f902b0c6ddfeb0246329ea4f7a79eae9b)
> Fix jinja template

- pyproject.toml
- src/pyloobins/models.py
- [Add LOOBinsGroup class](https://github.com/infosecB/LOOBins/commit/5d55ad9c772d1e1608e8a09707f64fd103df81fe)
- [Bump version](https://github.com/infosecB/LOOBins/commit/e29f2ccc3394257fda9490cddad466682482c781)
> Dev json dump

- LOOBins/tmutil.yml
- [Add LOOBin for tmutil](https://github.com/infosecB/LOOBins/commit/be53087b28c5dc47d19c7c709343fbe4deb1e985)
- Closes #63
> Add LOOBin for tmutil

- LOOBins/textutil.yml
Re-read the content and there were a few spelling mistakes
> Corrected spelling mistakes in textutil.yml

- LOOBins/plutil.yml
- Closes #41 
- [Add plutil](https://github.com/infosecB/LOOBins/commit/fae312c957e81eda296229ca6d13809ad5c45732)
> 41 add loobin for plutil

- LOOBins/open.yml
[Add LOOBin for open](https://github.com/infosecB/LOOBins/commit/f4394e4629f6c257392fac82b4d88b4859d3c8f1)
> Add LOOBin for open

- LOOBins/osacompile.yml
- [Add LOOBin for osacompile](https://github.com/infosecB/LOOBins/commit/0887048b8ae0cd8cf34c17e7e57b123329d24d8c)
- Closes #57
> Add LOOBin for osacompile

- src/pyloobins/models.py
- [Fix combine methods to handle none values](https://github.com/infosecB/LOOBins/commit/9176a3ee2064fb33687236cb9fd4affe1db81aae)
> Fix combine methods to handle none values

- LOOBins/lsregister.yml
- [Add LOOBin for lsregister](https://github.com/infosecB/LOOBins/pull/107/commits/a3d38277e28e985fda9e17109d301632e7c92ff9)
- Closes #17
> Add LOOBin for lsregister

- LOOBins/profiles.yml
- Add [profiles.yml](https://github.com/infosecB/LOOBins/commit/662e4ce58474b0accdee0b5c96f23d41152d7e94)
- closes #59
> Add LOOBin for profiles

- LOOBins/tclsh.yml
- [Add LOOBin for tclsh](https://github.com/infosecB/LOOBins/commit/3d88dde0fdd21eedbac9fe9eb61b8269a0a96fa0)
- Closes #109
> Add LOOBin for tclsh

- LOOBins/dns-sd.yml
> Add LOOBin for dns-sd

- pyproject.toml
- src/pyloobins/cli.py
- src/pyloobins/util.py
- tests/test_models.py
- [Update cli](https://github.com/infosecB/LOOBins/commit/bc87e9d530fd83a49a7c474939f4280fdcab0d21)
- [Add optional name arg to make_template function](https://github.com/infosecB/LOOBins/commit/1abef03b21f673a93761d2049af9d135ee963be8)
- [Fix test](https://github.com/infosecB/LOOBins/commit/68d94a6164c0b983c175a4f9204b586172ef36ec)
- [Bump version to 0.1.6](https://github.com/infosecB/LOOBins/commit/4ffcb1c44ce211957abe6ea059931114d0a80f0b)
> Multiple pyloobin fixes / updates

- docs/pyloobins/README.md
- pyproject.toml
- src/pyloobins/cli.py
- [Update package doc location](https://github.com/infosecB/LOOBins/commit/4e24154a40a852a7e14fbec204c3df3a557fc690)
- [Add README for PyLOOBins](https://github.com/infosecB/LOOBins/commit/222a2ba904fbda08c8c63fb90d456a6f32659ad2)
- [Change file arg to path](https://github.com/infosecB/LOOBins/commit/3de25849138b647690326b8dfe4f7a3681e45f89)
- [Bump version to v0.1.7](https://github.com/infosecB/LOOBins/pull/115/commits/7e89b65f5c4108a2e83bcd47650af9551d27ed6b)
> Update cli docs

- .github/workflows/validate_loobin_schema.yml
- docs/pyloobins/README.md
- [Fix validate_loobin_schema action](https://github.com/infosecB/LOOBins/commit/64af447b923a0b6a55c9108776e8324ffc01d408)
- [Update README](https://github.com/infosecB/LOOBins/commit/beb8181ae06c31ac0659ab38f07bf63ea21355d5)
> Fix validate_loobin_schema action

- src/pyloobins/cli.py
- [Fix validate def arg](https://github.com/infosecB/LOOBins/commit/b1e15d0bbe2cba3de4e1133797c40ff9756fffd8)
> Fix validate def arg

- LOOBins/safaridriver.yml
- Closes #102
- [Add LOOBin for safaridriver](https://github.com/infosecB/LOOBins/commit/60b785702a3949ee611ad60293490277a24c703b)
> Add LOOBin for safaridriver

- LOOBins/hdiutil.yml
- [Adding YAML file for binary hdiutil](https://github.com/infosecB/LOOBins/pull/120/commits/17bae51b6442934a888430cd1dcc122f33a212e5)
- Closes #51
> Add hdiutil.yml

- pyproject.toml
- src/pyloobins/util.py
[Fix PyLOOBins LOOBins site dir path definition](https://github.com/infosecB/LOOBins/commit/0a6b8d830a898a7ef97c3ba1434a16ec382c76ee)
> Fix PyLOOBins LOOBins site dir path definition 

- .github/workflows/validate_loobins.yml
- LOOBins/dsexport.yml
- LOOBins/nvram.yml
- LOOBins/spctl.yml
- LOOBins/sqlite3.yml
- README.md
- [Add LOOBin for sqlite3](https://github.com/infosecB/LOOBins/commit/5d55b50a1d944a8caa11e1dd35072764bff0da38)
- [Add LOOBin for dsexport](https://github.com/infosecB/LOOBins/commit/63a8b2b04ba484cfac52cd42432553e94befff39)
- Closes #46 
- [Add LOOBin for spctl](https://github.com/infosecB/LOOBins/pull/126/commits/5a632a9a6b5519c7124b96adad075a4dc8282ebc)
- Closes #121 
- [Add LOOBin for nvram](https://github.com/infosecB/LOOBins/pull/126/commits/91d997374b6e436127fc96f8298798931807252d)
- Closes #98 
- [Rename validate_loobins action](https://github.com/infosecB/LOOBins/commit/26c688d6004c86043f0af486343d544972b48b56)
- [Update readme 1](https://github.com/infosecB/LOOBins/commit/3368ac032f304b345ad8fb33b428bca49264124e)
- [Update readme …
> Multiple loobins, readme updates, gitci tweaks

- LOOBins/open.yml
- LOOBins/osacompile.yml
- docs/pyloobins/README.md
- [Add full_description to open](https://github.com/infosecB/LOOBins/commit/2572a2e3d04ad3d262fecea7a8da2213a4d360be)
- [Add osacompile use case desc](https://github.com/infosecB/LOOBins/commit/32cfc7606f2238ad6be6e62e1ffd1e45dd3d0bcf)
- [Update sdk doc](https://github.com/infosecB/LOOBins/commit/a39c38915dcd9d7c22b0fdd30b05b88103b83f7b)
> Minor edits

- LOOBins/GetFileInfo.yml
- LOOBins/SetFile.yml
- LOOBins/csrutil.yml
- LOOBins/defaults.yml
- LOOBins/ditto.yml
- LOOBins/dscl.yml
- LOOBins/hdiutil.yml
- LOOBins/last.yml
- LOOBins/mdfind.yml
- LOOBins/networksetup.yml
- LOOBins/nscurl.yml
- LOOBins/osascript.yml
- LOOBins/softwareupdate.yml
- LOOBins/ssh-keygen.yml
- LOOBins/tclsh.yml
- LOOBins/tmutil.yml
- LOOBins/xattr.yml
- README.md
- pyproject.toml
- [Minor short_description edits](https://github.com/infosecB/LOOBins/commit/be239b554a2e21c05f5dc5910107599ac2a25952)
- [Sync README](https://github.com/infosecB/LOOBins/commit/d38a27e18ad136a134cbf9837cef8d08954a91ed), [Update README](https://github.com/infosecB/LOOBins/commit/dcc5e70887f06acbbc268d3d061587d57bde1483)
- [Add LOOBin for defaults](https://github.com/infosecB/LOOBins/pull/128/commits/ddb1bc8ef15a6fd2eca755d0d71fe8fb8e4f9e02)
- Closes #44 
- [Bump version to v1.0.0](https://github.com/infosecB/LOOBins/commit/fd56d598478d58a651303607256e0aab3234c540)
> Release prep

- LOOBins/launchctl.yml
- Added Launchctl binary yaml file.
- Closes #16
> Add LOOBin for launchctl

- LOOBins/dns-sd.yml
- LOOBins/mdfind.yml
- [Update dns-sd](https://github.com/infosecB/LOOBins/commit/fc1de2d00ec34144ebd522aee382e5c82fb43389)
- [Update mdfind](https://github.com/infosecB/LOOBins/commit/8a0358dae33eb7c7d8b438f486f44856a9f1400a)
- Closes #131
> Update mdfind, dns-sd

- pyproject.toml
- [Bump to v1.1](https://github.com/infosecB/LOOBins/commit/a6c979872063823bff180fb98ed110869ee9457f)
> Bump to v1.1

- .github/workflows/pre_release.yml
- [add workflow dispatch trigger](https://github.com/infosecB/LOOBins/commit/7a9e7e97af1a210348631f4beaf0217d91142bba)
> add workflow dispatch trigger

- LOOBins/kextstat.yml
Add YAML file for binary kextstat
> Add YAML file for binary kextstat

- LOOBins/ioreg.yml
> ioreg fix spelling errors

- LOOBins/sw_vers.yml
sw_vers binary for discovery. System Information Discovery T1082.
> Add YAML file for binary sw_vers

- LOOBins/sfltool.yml
sfltool with background task manager. 
Demystifying (& Bypassing) macOS's Background Task Management - Patrick Wardle
> Add YAML file for binary sfltool

- LOOBins/caffeinate.yml
And clarify usage with an example
> Add the "Defense Evasion" tactic to caffeinate

- LOOBins/osacompile.yml
According to the use cases, the command and control (ingress tool transfer) and Resource Development tactics are more appropriate. Thoughts?
> Change tactics in osacompile

- pyproject.toml
- src/pyloobins/cli.py
- src/pyloobins/models.py
- src/pyloobins/util.py
- tests/test_models.py
- tests/test_util.py
- Bumped version in Poetry
- Fixed breaking changes associated with several models
- Updated tests
> Migrate to Pydantic v2

- src/pyloobins/cli.py
Adds --version argument to cli:
```
>>> pyloobins --version
PyLOOBins, version 1.4.3
```
> Add version argument to cli

- .github/workflows/release.yml
- pyproject.toml
- [Add python v3.12 to tox test](https://github.com/infosecB/LOOBins/commit/1027f41d73894dec5003ccdb26ea9bcdf85d0f89)
- [Update ci commands](https://github.com/infosecB/LOOBins/commit/23ae39c1b06973c0a47ac9663557b29b406bc3c0)
> Fix test ci

- LOOBins/nscurl.yml
Added a Tactic, added two more Use Cases, and added a Resource
> Updated YAML file for nscurl

- pyproject.toml
[bump to version 1.7](https://github.com/infosecB/LOOBins/commit/eb35750df579ef7524467c0121e0d3cb99da5985)
> bump to version 1.7

- LOOBins/chflags.yml
> Adding chflags command

- LOOBins/dscl.yml
- LOOBins/mdfind.yml
- LOOBins/osascript.yml
- LOOBins/security.yml
- LOOBins/sfltool.yml
- LOOBins/sqlite3.yml
- LOOBins/tmutil.yml
- LOOBins/xattr.yml
Hi,
I'm not sure if it's allowed to link detection rules related to the LOOBINs, if not feel free to close the PR.
> Add detections that are applicable with Jamf Protect

- LOOBins/dns-sd.yml
- LOOBins/ioreg.yml
- LOOBins/launchctl.yml
- LOOBins/nscurl.yml
- LOOBins/swift.yml
- LOOBins/sysctl.yml
- LOOBins/system_profiler.yml
- LOOBins/systemsetup.yml
After the first PR and the positive feedback i'm linking additional LOOBins to Jamf Protect where a open-source detection is in place.
> Jamf Protect: Linking additional LOOBins to Jamf Protect

- LOOBins/codesign.yml
As listed in #48 that help was wanted for the `codesign` loobin, here with a initial version.
> Adding initial version of the `codesign` loobin

- LOOBins/nscurl.yml
Adding Sigma Detection link to nscurl.yml
> Adding Sigma Detection to nscurl.yml

- LOOBins/pbpaste.yml
Adding Sigma detection rule and resource blog post link to pbpaste.yml
> Adding Sigma detection and resource link to pbpaste.yml
